### ISSUE TITLE
Ignoring a rule also ignores completely unrelated rules

### ISSUE THREAD

**Issue by jankodera-ps** [Redocly/redocly-cli#1063]
**Describe the bug**
`--skip-rule` seems to skip all rules instead of just the rule that is specified to be skipped.

**To Reproduce**
1. Given this [repro.yaml](https://gist.github.com/jankodera-ps/5a580bb371256f38c93fb8a7ffeefa2e)
2. Run `redocly lint repro.yaml`
4. See two errors (this is expected): missing scopes (`spec` rule), missing 4XX response (`operation-4xx-response` rule).
5. Run `redocly lint --skip-rule=operation-4xx-response repro.yaml`
6. Get `Woohoo! Your OpenAPI definitions are valid.`

**Expected behavior**
Step 6 should return one error, from `spec` rule.

**Redocly Version(s)**
1.0.0-beta.125

**`Node.js` Version(s)**
19.9.0

**Comment by Orest-Yastremskyy** [comment]
Hi @jankodera-ps,

I believe that this issue occurs because of the wrong order of parameters passed to the lint command.

What I mean is if you pass the API definition file first and additional parameters after (e.g. ` redocly lint repro.yaml --skip-rule=operation-4xx-response` instead of `redocly lint --skip-rule=operation-4xx-response repro.yaml`), everything works fine. In case you pass additional parameters first, you will get the invalid validation of the API definition:

![image](https://user-images.githubusercontent.com/96121440/235080777-217d7cc9-c268-450b-b318-d99fabf1b431.png)


Hope it helps.

**Comment by jankodera-ps** [comment]
Okay, happy to see it can be easily fixed, but have to say this behavior is definitely unexpected.

**Comment by tatomyr** [comment]
The issue here is that the `--skip-rule` option expects an array, so it recognises the positional argument as a part of the array. This is a known [issue](https://github.com/yargs/yargs/issues/1848) in **yargs** library, which we use here for parsing the arguments. 

By the way, the behaviour will change after this MR: https://github.com/Redocly/redocly-cli/pull/1055 (it will fail with a message that no APIs were provided).

One option to fix this is to use the parser configuration setting `'greedy-arrays': false` (which I believe will eventually become **yargs** default). However, it will affect our current users' scripts.

**Comment by jankodera-ps** [comment]
Right, in this context the problem now makes sense. What is really weird is that this issue can be reproduced even with `--skip-rule=spec-components-invalid-map-name`, which I really wouldn't expect to consume additional positional arguments beyond the first one explicitly indicated to belong to the `--skip-rule`.

I know this kind of falls outside the scope of this project as it is a problem in a dependency library and you already have a solution as @tatomyr indicated above, but would it make sense to consume just one argument with comma-separated rule names? That would resolve the ambiguity while providing the same functionality.

**Comment by tatomyr** [comment]
@jankodera-ps this would be an option if we don't have to support the current syntax (with spaces as separators). And we have other commands with similar behaviour also. We will think of possible solutions.

Anyways, thank you for bringing attention to this!

**Comment by tatomyr** [comment]
Should be fixed in `beta.127`.
