### ISSUE TITLE
Update Redocly config validation

### ISSUE THREAD

**Issue by tatomyr** [Redocly/redocly-cli#1076]
Redocly CLI should validate the universal Redocly config correctly. We have to update the type tree to be in sync with JSONSchema we use to validate the config in Portal.

**Comment by lornajane** [comment]
Would this include changing the configuration to expect theme config like:

```
features:
  openapi:
    theme:
```

Currently this tool expects `theme.openapi.theme` rather than `features.openapi.theme`. Similarly, the command line options are in the format `--theme.options.theme.*...` - Looking at the other configuration docs, I think that should be `--features.openapi.theme.*...`. 

My question is whether we'd cover that change in this issue, or if I should open another to follow up on that.

Related issues: #1065 #1073 #982

**Comment by tatomyr** [comment]
@lornajane Yes, this about supporting things that aren't directly related to Redocly CLI. In the end we should see correct warnings about wrong fields in CLI/VSCode.

**Comment by lornajane** [comment]
Does this mean that I can do `redocly lint redocly.yaml`, or does the tool always validate the config when it's linting something else? I am not exactly sure how to use the feature.

**Comment by tatomyr** [comment]
@lornajane sorry, I somehow missed your question.  It means that whenever you use a redocly command (i.e. `redocly lint openapi.yaml`) we validate your config (if we can find one) and warn if something is wrong in the config.
<img width="536" alt="Screenshot 2023-06-23 at 13 58 02" src="https://github.com/Redocly/redocly-cli/assets/11423792/cb4ac063-008f-43a0-b149-513a37bb2ddb">
