### ISSUE TITLE
Disable rules on a per-path basis

### ISSUE THREAD

**Issue by manuelmaurer** [Redocly/redocly-cli#1110]
**Is your feature request related to a problem? Please describe.**
The default ruleset contains operation-4xx-response which in general I like. However, I designed some APIs with paths that do not comply to this rule, because it does not make sense. For example healthchecks, public-key downloads (e.g. for JWT validation) etc.

All those paths have no user input, that is they are GET and do not contain any parameter or requirements (e.g. no auth). Therefore I do not see how they can result in an 4xx response.

**Describe the solution you'd like**
It would be helpful to disable this rule (probably others as well) on a per-path basis. This would allow me to whitelist relevant paths and still have this warning on all other paths.

**Describe alternatives you've considered**
Disabling the rule altogether works (and is my usual go-to solution). Adding a dummy 4xx-response also works, but that's just wrong (literally).

**Comment by lornajane** [comment]
I think what you're describing is functionality covered by the ignore file. This allows you to add exceptions for specific instances of an "error" to a list of things to ignore, so that you can keep your rules turned on but deactivate them for special situations such as what you describe here. You can read more in the [lint command docs](https://redocly.com/docs/cli/commands/lint/#generate-ignore-file).

I'll close the issue since I think this is the information you need, but let us know if you need anything else!
