### ISSUE TITLE
Add lint option like "max-warnings"

### ISSUE THREAD

**Issue by leonovi** [Redocly/redocly-cli#1129]
**Is your feature request related to a problem? Please describe.**

I don't think this is a big problem, but this functionality seems to me very suitable for this package.

**Describe the solution you'd like**

I would like to have the `max-warnings` option for the lint command.

https://github.com/Redocly/redocly-cli/blob/main/packages/cli/src/commands/lint.ts#L126

By the link, the place where the script returns 0 or 1, depending on the number of errors:
```
totals.errors === 0
```

It would be great to make it look something like this:
```
process.exit(
  (
    totals.errors === 0 && 
--> total.warnings < argv['max-warnings'] <--
  ) || argv['generate-ignore-file'] ? 0 : 1
)
```

**Describe alternatives you've considered**

I had to change the strictness rules from warn to error

**Comment by lornajane** [comment]
We currently have `max-problems` to set an upper limit on how many are detected; this can be useful if you want to see more or fewer errors (the default value is 100).

If your use case is to let you know if you have more than "X" number of errors, a more targeted approach could be to generate an ignore file for the errors/warnings you're already aware of, so that only new ones will show in the linting output. (docs for ignore file: https://redocly.com/docs/cli/commands/lint/#generate-ignore-file).

Would either of these cover your use case? If not, can you say a bit more about what you're trying to do?

**Comment by leonovi** [comment]
Now your script returns code 0 when there are no errors and code 1 when there is at least one error. I would like the script to return 1 when the "max-warnings" option is exceeded

**Comment by leonovi** [comment]
In our ci, the check is considered not passed if the script response code is not 0. And we want to make the openapi linting fall even if there are warnings

**Comment by lornajane** [comment]
I think I understand the question better now, thanks for the extra information. We adopted industry-standard behaviour of only exiting with an error code if there was an error - any warnings are shown in the output. I think you have a couple of options to achieve what you want:
* check the output of the tool, parse the line with the number of warnings/errors and apply your own logic
* the other option is what I think you already chose - making the warnings into errors since they are an actual problem

**Comment by lornajane** [comment]
I'll close this since I don't think there's more to for us to do on this, but do let us know if you need anything else.
