### ISSUE TITLE
v1.1.0 fails to install with babel error

### ISSUE THREAD

**Issue by mattoni** [Redocly/redocly-cli#1262]
**Describe the bug**

Using npx, the latest version fails to run.

**To Reproduce**

1. `npx @redocly/cli@1.1.0`

**Expected behavior**

redocly works

**Logs**

![image](https://github.com/Redocly/redocly-cli/assets/5110855/551639c1-f390-4bd5-b0ad-5c20c1749906)

**Redocly Version(s)**
v1.1.0

**`Node.js` Version(s)**
v19.0.0

**Additional context**

Looks like a downstream dependency is asking for `@babel/types@^7.22.18` which doesn't exist.

**Comment by joacocoba** [comment]
I'm also facing the same issue, we're using the node version 15.4.0 and we had to use an older version of redocly/cli in order to make it work. The command we've used is this: `npx @redocly/cli@1.0.2 lint oas/oas.yaml`. 

Image of the error: <img width="671" alt="Screenshot 2023-09-14 at 12 48 58" src="https://github.com/Redocly/redocly-cli/assets/38257996/9390acbc-bb99-4cbf-a3f6-4f7ae3fe4a9a">

Image of the success after executing that command:
![Captura de pantalla 2023-09-14 a la(s) 12 49 30 p m](https://github.com/Redocly/redocly-cli/assets/38257996/2b40b079-e69f-4e98-972e-7438adb5bcc8)

My question is that the 1.1.0 is not compatible with versions of node older than 16?

**Comment by mattoni** [comment]
@tatomyr I'm running inside a docker container with alpine linux, but it is easily reproducible on my host machine by using `npx @redocly/cli@1.1.0 ....` outside of my project. It fails to install because the babel version requested by a downstream repository does not exist. Older versions of redocly work just fine.

**Comment by Billiam** [comment]
I think this has been corrected upstream. @babel/types@7.22.19 has been published, and redocly's dependencies now point to that one.

**Comment by tatomyr** [comment]
Looks like now it is pointing to @babel/types@7.22.19 as @Billiam has mentioned above. Can you please @mattoni and @joacocoba check if the issue has gone?

**Comment by mattoni** [comment]
Appears to be working again, thank you.
