### ISSUE TITLE
Validate spec during the preview

### ISSUE THREAD

**Issue by konstantin-smolyakov-idt** [Redocly/redocly-cli#292]
**Is your feature request related to a problem? Please describe.**
In the JS community it's quite common to have a live-reload functionality that'll lint JS files while running the development server. In case of redocly CLI, the developer can't preview the spec and see validation rules at the same time. 

**Describe the solution you'd like**
It would be nice to both update the preview and re-run linting rules on source file change.

**Comment by adamaltman** [comment]
I agree. I went up with two tabs of terminal running to do this now. And our docs are very forgiving, so it's easy to not see a mistake in the preview mode.

**Comment by adamaltman** [comment]
Now that we have a VS Code extension, I find this less necessary (personally). If you don't use VS Code, this would still be important.

**Comment by lornajane** [comment]
Mixing these two functions into one command with mixed output may confuse more users than it helps. In the years since this suggestion I think good practice has moved more towards pipelines and commands that do just one thing, so I'm closing this issue since we're now unlikely to implement a combined feature like this one.
