### ISSUE TITLE
Validate 'redocly/cli` package before publishing to npm and workflows

### ISSUE THREAD

**Issue by SmoliyY** [Redocly/redocly-cli#732]
### Description 

`redocly/cli` [release](https://github.com/Redocly/redocly-cli/pull/730) `1.0.0-beta101` was failed due to publishing code that use package that do not exist in `packages/cli/package.json`, but instead this package exist in root `package.json`. Also we need to add test to check `workflows` functionality

### Solution

- Add check (e.g eslint rule) that would check if package exist in `packages/cli/package.json`
- Add test that would build same packages that published to `npm`
- Add more tests for `workflows` functionality

**Comment by tatomyr** [comment]
Turns out `npm pack` from [here](https://github.com/Redocly/redocly-cli/pull/773/files#diff-95557d53bf91069e59d82b9d8fcfaf52ec84a762858983edd5ef3c9b3e4c8191R65) doesn't include the corresponding `openapi-core` what leads to inconsistency in this test. I'm reopening this issue as I  had to comment out this job and this should be fixed.
