### ISSUE TITLE
Update outdated version warning in output

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#779]
**Is your feature request related to a problem? Please describe.**

There is no good way to alert users to new updates in the CLI tool.

**Describe the solution you'd like**

I'd like part of the CLI output to check and show the current version versus the running version. If the current version is different, to show this output... something like

```bash
A new version of Redocly CLI (1.0.0-beta.105) is available.
Update now: npx @redocly/cli@latest upgrade
Changelog: {TODO}
```

Optimal would be an integrated changelog information and show every change between the version installed and the current version.

**Describe alternatives you've considered**

None yet.

**Additional context**

Consider also the JSON output format so that it can be parsed and programmatically displayed in Workflows.

**Comment by RomanHotsiy** [comment]
`redoc-cli` team just opened a PR for this too: https://github.com/Redocly/redoc/pull/2100/files. We can use same implementation.

**Comment by tatomyr** [comment]
Had to revert this as lint fails in Workflows.

**Comment by IgorKarpiuk** [comment]
This is fails in Workflows because webpack doesn't work with `import-lazy`
- We can fork [this repo](https://github.com/yeoman/update-notifier)
- Or we can use [this fork](https://github.com/datacrafts-io/update-notifier-webpack), but it has not been updated for some time
- We can create our own solution 

@tatomyr @RomanHotsiy

**Comment by lornajane** [comment]
For the target audience using the CLI either themselves at the terminal, or in a CI setup, the version information and upgrade prompt are really valuable. However since some of our commands output JSON or other formats, would we consider sending this to `stderr`, or maybe only fitting the output to a subset of commands? And would either of those approaches help with the problem we encountered previously where Workflows tripped up on the extra output?
