### ISSUE TITLE
Error message shows up: 'Every API should have security defined on the root level or for each operation'

### ISSUE THREAD

**Issue by AviandraPutri-Jubelio** [Redocly/redocly-cli#877]
I used to split my openapi files using this 'create-openapi-method', it was usually ok, but today, September 19th, this error notification shows up and i don't understand why. Could you please explain this error to me?

![image](https://user-images.githubusercontent.com/111033787/190943520-36eedd7b-49d2-458d-8d90-6d125121d124.png)

**Comment by RomanHotsiy** [comment]
You can either fix this issue by adding `security: []` to the root of your definition or by changing the rule severity to `warn` in the .redocly.yaml file:

```
rules:
  security-defined: warn
```

See more details here: https://redocly.com/docs/cli/rules/security-defined/#security-defined

Sorry for the inconvenience. We introduced a small breaking change.
We're releasing 1.0.0 soon and won't do breaking changes since then 🙌

**Comment by AviandraPutri-Jubelio** [comment]
ok i'll try it first, thank you for answering my question

**Comment by AviandraPutri-Jubelio** [comment]
it solved, thank youuu
